### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by adeelakram03** [handworker222/HEMS_RL#1]
Hi Dear, Can you kindly also provide the dataset for training and testing ?

**Comment by handworker222** [comment]
Hi, thanks for your interest. Please check the main repo for data and details: https://github.com/ShuhuaGao/Hybrid-HEM. You may also check the [full paper](https://www.researchgate.net/profile/Shuhua-Gao/publication/375209389_A_Hybrid_Approach_for_Home_Energy_Management_With_Imitation_Learning_and_Online_Optimization/links/6603ac515c41c3139dae39ba/A-Hybrid-Approach-for-Home-Energy-Management-With-Imitation-Learning-and-Online-Optimization.pdf) for more information.
